// Base URL for team logos
const baseUrl = "https://raw.githubusercontent.com/elistandard/ultimateDynasties/main/college-mens/college-mens-logos/";

// Logo mapping for teams
const logoMapping = {
    "Alabama-Huntsville": `${baseUrl}Alabama-Huntsville.jpeg?raw=true`,
    "Arizona": `${baseUrl}Arizona.png?raw=true`,
    "Auburn": `${baseUrl}Auburn.jpg?raw=true`,
    "BYU": `${baseUrl}BYU.png?raw=true`,
    "Boston College": `${baseUrl}Boston College.gif?raw=true`,
    "British Columbia": `${baseUrl}British Columbia.jpg?raw=true`,
    "Brown": `${baseUrl}Brown.jpeg?raw=true`,
    "Cal Poly SLO": `${baseUrl}Cal Poly SLO.jpg?raw=true`,
    "UC San Diego": `${baseUrl}UC San Diego.jpg?raw=true`,
    "UC Santa Barbara": `${baseUrl}UC Santa Barbara.jpg?raw=true`,
    "UC Santa Cruz": `${baseUrl}UC Santa Cruz.jpg?raw=true`,
    "California": `${baseUrl}California.jpg?raw=true`,
    "Carleton": `${baseUrl}Carleton.png?raw=true`,
    "Carnegie Mellon": `${baseUrl}Carnegie Mellon.png?raw=true`,
    "Case Western Reserve": `${baseUrl}Case Western Reserve.png?raw=true`,
    "Central Florida": `${baseUrl}Central Florida.png?raw=true`,
    "Chabot Community College": `${baseUrl}Chabot Community College.jpeg?raw=true`,
    "Cincinnati": `${baseUrl}Cincinnati.png?raw=true`,
    "Colorado College": `${baseUrl}Colorado College.jpg?raw=true`,
    "Colorado State": `${baseUrl}Colorado State.png?raw=true`,
    "Colorado": `${baseUrl}Colorado.png?raw=true`,
    "Connecticut": `${baseUrl}Connecticut.jpg?raw=true`,
    "Cornell": `${baseUrl}Cornell.jpg?raw=true`,
    "Columbia": `${baseUrl}Columbia.png?raw=true`,
    "Dartmouth": `${baseUrl}Dartmouth.png?raw=true`,
    "Delaware": `${baseUrl}Delaware.jpeg?raw=true`,
    "Duke": `${baseUrl}Duke.jpg?raw=true`,
    "East Carolina": `${baseUrl}East Carolina.jpeg?raw=true`,
    "Eastern Michigan": `${baseUrl}Eastern Michigan.jpg?raw=true`,
    "Florida State": `${baseUrl}Florida State.gif?raw=true`,
    "Florida": `${baseUrl}Florida.png?raw=true`,
    "George Washington": `${baseUrl}George Washington.jpeg?raw=true`,
    "Georgetown": `${baseUrl}Georgetown.png?raw=true`,
    "Georgia Tech": `${baseUrl}Georgia Tech.jpeg?raw=true`,
    "Georgia": `${baseUrl}Georgia.jpeg?raw=true`,
    "Glassboro": `${baseUrl}Glassboro State.jpg?raw=true`,
    "Harvard": `${baseUrl}Harvard.jpg?raw=true`,
    "Illinois": `${baseUrl}Illinois.jpg?raw=true`,
    "Indiana": `${baseUrl}Indiana.png?raw=true`,
    "Iowa State": `${baseUrl}Iowa State.png?raw=true`,
    "Iowa": `${baseUrl}Iowa.jpeg?raw=true`,
    "James Madison": `${baseUrl}James Madison.jpeg?raw=true`,
    "Kansas": `${baseUrl}Kansas.jpeg?raw=true`,
    "LSU": `${baseUrl}LSU.jpg?raw=true`,
    "Las Positas College": `${baseUrl}Las Positas.png?raw=true`,
    "Luther": `${baseUrl}Luther.png?raw=true`,
    "Maryland": `${baseUrl}Maryland.png?raw=true`,
    "Massachusetts": `${baseUrl}Massachusetts.jpeg?raw=true`,
    "McGill": `${baseUrl}McGill.jpg?raw=true`,
    "Michigan State": `${baseUrl}Michigan State.jpg?raw=true`,
    "Michigan": `${baseUrl}Michigan.png?raw=true`,
    "Middlebury": `${baseUrl}Middlebury.webp?raw=true`,
    "Minnesota-Duluth": `${baseUrl}Minnesota-Duluth.jpeg?raw=true`,
    "Minnesota": `${baseUrl}Minnesota.png?raw=true`,
    "Missouri": `${baseUrl}Missouri.png?raw=true`,
    "MIT": `${baseUrl}MIT.jpg?raw=true`,
    "NC State": `${baseUrl}NC State.jpg?raw=true`,
    "UNC Wilmington": `${baseUrl}UNC Wilmington.jpg?raw=true`,
    "North Carolina": `${baseUrl}North Carolina.png?raw=true`,
    "North Texas": `${baseUrl}North Texas.jpg?raw=true`,
    "Northeastern": `${baseUrl}Northeastern.jpg?raw=true`,
    "Northwestern": `${baseUrl}Northwestern.png?raw=true`,
    "Notre Dame": `${baseUrl}Notre Dame.jpg?raw=true`,
    "Oberlin": `${baseUrl}Oberlin.png?raw=true`,
    "Ohio State": `${baseUrl}Ohio State.jpg?raw=true`,
    "Ohio": `${baseUrl}Ohio.jpeg?raw=true`,
    "Oregon State": `${baseUrl}Oregon State.png?raw=true`,
    "Oregon": `${baseUrl}Oregon.png?raw=true`,
    "Ottawa": `${baseUrl}Ottawa.png?raw=true`,
    "Penn State": `${baseUrl}Penn State.jpg?raw=true`,
    "Penn": `${baseUrl}Penn.png?raw=true`,
    "Pittsburgh": `${baseUrl}Pittsburgh.png?raw=true`,
    "Princeton": `${baseUrl}Princeton.jpeg?raw=true`,
    "Purdue": `${baseUrl}Purdue.jpeg?raw=true`,
    "Queen's": `${baseUrl}Queen's.png?raw=true`,
    "Rice": `${baseUrl}Rice.webp?raw=true`,
    "Rutgers": `${baseUrl}Rutgers.jpeg?raw=true`,
    "SUNY Albany": `${baseUrl}SUNY Albany.jpeg?raw=true`,
    "SUNY Binghamton": `${baseUrl}SUNY Binghamton.jpeg?raw=true`,
    "SUNY Purchase": `${baseUrl}SUNY Purchase.png?raw=true`,
    "SW Missouri State": `${baseUrl}SW Missouri State.png?raw=true`,
    "Saint Louis": `${baseUrl}Saint Louis.jpeg?raw=true`,
    "Salisbury": `${baseUrl}Salisbury.jpeg?raw=true`,
    "Southern California": `${baseUrl}Southern California.jpg?raw=true`,
    "Stanford": `${baseUrl}Stanford.png?raw=true`,
    "Swarthmore": `${baseUrl}Swarthmore.png?raw=true`,
    "Syracuse": `${baseUrl}Syracuse.png?raw=true`,
    "Texas A&M": `${baseUrl}Texas A&M.jpg?raw=true`,
    "Texas State": `${baseUrl}Texas State.jpg?raw=true`,
    "Texas": `${baseUrl}Texas.jpg?raw=true`,
    "Tufts": `${baseUrl}Tufts.png?raw=true`,
    "Tulane": `${baseUrl}Tulane.jpeg?raw=true`,
    "UC Davis": `${baseUrl}UC Davis.jpeg?raw=true`,
    "UCLA": `${baseUrl}UCLA.jpg?raw=true`,
    "UT Dallas": `${baseUrl}UT Dallas.png?raw=true`,
    "Utah State": `${baseUrl}Utah State.jpeg?raw=true`,
    "Utah": `${baseUrl}Utah.jpg?raw=true`,
    "Vermont": `${baseUrl}Vermont.jpg?raw=true`,
    "Victoria": `${baseUrl}Victoria.jpg?raw=true`,
    "Virginia": `${baseUrl}Virginia.jpg?raw=true`,
    "Virginia Tech": `${baseUrl}Virginia Tech.jpeg?raw=true`,
    "WashU": `${baseUrl}WashU.jpg?raw=true`,
    "Washington": `${baseUrl}Washington.jpg?raw=true`,
    "Wesleyan": `${baseUrl}Wesleyan.png?raw=true`,
    "Western Washington": `${baseUrl}Western Washington.jpg?raw=true`,
    "Whitman": `${baseUrl}Whitman.jpg?raw=true`,
    "Williams": `${baseUrl}Williams.jpg?raw=true`,
    "William & Mary": `${baseUrl}William & Mary.jpg?raw=true`,
    "Wisconsin": `${baseUrl}Wisconsin.jpg?raw=true`,
    "Wisconsin-Milwaukee": `${baseUrl}Wisconsin-Milwaukee.jpg?raw=true`,
    "Winona State": `${baseUrl}Winona State.jpg?raw=true`,
    "Yale": `${baseUrl}Yale.png?raw=true`
};

// Color data for teams
const colorData = [
    { team: "Alabama-Huntsville", color: "#1f51f3" },
    { team: "Arizona", color: "#D94B3E" },
    { team: "Auburn", color: "#f0812a" },
    { team: "BYU", color: "#FFD700" },
    { team: "Boston College", color: "#bc0032" },
    { team: "British Columbia", color: "#CDA900" },
    { team: "Brown", color: "#964B00" },
    { team: "Cal Poly SLO", color: "#68b0a7" },
    { team: "California", color: "#1D315E" },
    { team: "Carleton", color: "#c1172a" },
    { team: "Carnegie Mellon", color: "#64AE46" },
    { team: "Case Western Reserve", color: "#2AC1DF" },
    { team: "Central Florida", color: "#FEB934" },
    { team: "Chabot Community College", color: "#d6b002" },
    { team: "Cincinnati", color: "#E00122" },
    { team: "Colorado College", color: "#1A4B84" },
    { team: "Colorado State", color: "#1E4D2B" },
    { team: "Colorado", color: "#CFB87C" },
    { team: "Connecticut", color: "#000E2F" },
    { team: "Cornell", color: "#B31B1B" },
    { team: "Columbia", color: "#9BCDD2" },
    { team: "Dartmouth", color: "#00693E" },
    { team: "Delaware", color: "#FFD700" },
    { team: "Duke", color: "#003087" },
    { team: "East Carolina", color: "#592A8A" },
    { team: "Eastern Michigan", color: "#006633" },
    { team: "Florida State", color: "#782F40" },
    { team: "Florida", color: "#0021A5" },
    { team: "George Washington", color: "#A51E37" },
    { team: "Georgetown", color: "#041E42" },
    { team: "Georgia Tech", color: "#B3A369" },
    { team: "Georgia", color: "#BA0C2F" },
    { team: "Glassboro", color: "#1A4B84" },
    { team: "Harvard", color: "#A51E37" },
    { team: "Illinois", color: "#E84A27" },
    { team: "Indiana", color: "#990000" },
    { team: "Iowa State", color: "#C8102E" },
    { team: "Iowa", color: "#000000" },
    { team: "James Madison", color: "#46166B" },
    { team: "Kansas", color: "#0051BA" },
    { team: "LSU", color: "#461D7C" },
    { team: "Las Positas College", color: "#1A4B84" },
    { team: "Luther", color: "#1A4B84" },
    { team: "Maryland", color: "#E21836" },
    { team: "Massachusetts", color: "#881C1C" },
    { team: "McGill", color: "#ED1C24" },
    { team: "Michigan State", color: "#18453B" },
    { team: "Michigan", color: "#00274C" },
    { team: "Middlebury", color: "#1A4B84" },
    { team: "Minnesota-Duluth", color: "#7A0019" },
    { team: "Minnesota", color: "#7A0019" },
    { team: "Missouri", color: "#F1B82D" },
    { team: "MIT", color: "#8A8B8C" },
    { team: "NC State", color: "#CC0000" },
    { team: "UNC Wilmington", color: "#FFD700" },
    { team: "North Carolina", color: "#7BAFD4" },
    { team: "North Texas", color: "#00853E" },
    { team: "Northeastern", color: "#000000" },
    { team: "Northwestern", color: "#4E2A84" },
    { team: "Notre Dame", color: "#0C2340" },
    { team: "Oberlin", color: "#1A4B84" },
    { team: "Ohio State", color: "#BB0000" },
    { team: "Ohio", color: "#006F71" },
    { team: "Oregon State", color: "#D73F09" },
    { team: "Oregon", color: "#154733" },
    { team: "Ottawa", color: "#1A4B84" },
    { team: "Penn State", color: "#041E42" },
    { team: "Penn", color: "#011F5B" },
    { team: "Pittsburgh", color: "#003594" },
    { team: "Princeton", color: "#FF8F00" },
    { team: "Purdue", color: "#C28E0E" },
    { team: "Queen's", color: "#1A4B84" },
    { team: "Rice", color: "#00205B" },
    { team: "Rutgers", color: "#CC0033" },
    { team: "SUNY Albany", color: "#1A4B84" },
    { team: "SUNY Binghamton", color: "#1A4B84" },
    { team: "SUNY Purchase", color: "#1A4B84" },
    { team: "SW Missouri State", color: "#1A4B84" },
    { team: "Saint Louis", color: "#1A4B84" },
    { team: "Salisbury", color: "#1A4B84" },
    { team: "Southern California", color: "#990000" },
    { team: "Stanford", color: "#8C1515" },
    { team: "Swarthmore", color: "#1A4B84" },
    { team: "Syracuse", color: "#D44500" },
    { team: "Texas A&M", color: "#500000" },
    { team: "Texas State", color: "#4F2683" },
    { team: "Texas", color: "#BF5700" },
    { team: "Tufts", color: "#3E8EDE" },
    { team: "Tulane", color: "#006633" },
    { team: "UC Davis", color: "#1A4B84" },
    { team: "UCLA", color: "#2774AE" },
    { team: "UT Dallas", color: "#1A4B84" },
    { team: "Utah State", color: "#1A4B84" },
    { team: "Utah", color: "#CC0000" },
    { team: "Vermont", color: "#1A4B84" },
    { team: "Victoria", color: "#1A4B84" },
    { team: "Virginia", color: "#232D4B" },
    { team: "Virginia Tech", color: "#861F41" },
    { team: "WashU", color: "#1A4B84" },
    { team: "Washington", color: "#4B2E83" },
    { team: "Wesleyan", color: "#1A4B84" },
    { team: "Western Washington", color: "#1A4B84" },
    { team: "Whitman", color: "#1A4B84" },
    { team: "Williams", color: "#1A4B84" },
    { team: "William & Mary", color: "#1A4B84" },
    { team: "Wisconsin", color: "#C5050C" },
    { team: "Wisconsin-Milwaukee", color: "#1A4B84" },
    { team: "Winona State", color: "#1A4B84" },
    { team: "Yale", color: "#00356B" }
];

// Raw data from CSV
const rawData = {
    "College Men's": [
        { Team: "Stanford", Year: 1984, Rank: 1, T_Rank: 1, Division: "College Men's" },
        { Team: "Glassboro", Year: 1984, Rank: 2, T_Rank: 2, Division: "College Men's" },
        // ... more data ...
    ],
    "College Women's": [
        { Team: "Kansas", Year: 1987, Rank: 1, T_Rank: 1, Division: "College Women's" },
        { Team: "UC Davis", Year: 1987, Rank: 2, T_Rank: 2, Division: "College Women's" },
        // ... more data ...
    ]
};

// Helper functions for data processing
function getTeamStats(team, division) {
    const data = rawData[division].filter(d => d.Team === team);
    return {
        appearances: data.length,
        championships: data.filter(d => d.Rank === 1).length,
        top3: data.filter(d => d.Rank <= 3).length,
        top5: data.filter(d => d.Rank <= 5).length,
        top10: data.filter(d => d.Rank <= 10).length,
        years: data.map(d => d.Year).sort((a, b) => a - b),
        rankings: data.map(d => ({ year: d.Year, rank: d.Rank, tRank: d.T_Rank }))
    };
}

function getDivisionStats(division) {
    const data = rawData[division];
    const teams = [...new Set(data.map(d => d.Team))];
    
    return teams.map(team => {
        const stats = getTeamStats(team, division);
        return {
            team,
            ...stats
        };
    }).sort((a, b) => b.championships - a.championships || b.top3 - a.top3);
}

function getYearlyRankings(division, year) {
    return rawData[division]
        .filter(d => d.Year === year)
        .sort((a, b) => a.Rank - b.Rank);
}